try mustache for if negation

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -2,8 +2,8 @@ name: dashpipe-build
 
 on:
   push:
-    branches: [ test-workflow ]
-    tags: 
+    branches: [test-workflow]
+    tags:
       - "v*.*.*"
 
 env:
@@ -11,40 +11,38 @@ env:
 
 jobs:
   build-linux:
-
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v2
+      - uses: actions/checkout@v2
 
-    - name: show ref
-      run: |
-        echo 1 $GITHUB_REF
-        git show --oneline --no-patch
-    
-    - name: verify tag check
-      if: ! startsWith(github.ref, 'refs/tags/')
-      run: |
-        echo "::error git checkout has no git tag"
-        exit 1
+      - name: show ref
+        run: |
+          echo 1 $GITHUB_REF
+          git show --oneline --no-patch
 
-    - name: Build
-      run: cargo build --verbose --release
+      - name: verify tag check
+        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
+        run: |
+          echo "::error git checkout has no git tag"
+          exit 1
 
-    - name: Run tests
-      run: cargo test --verbose --release
-    
-    - name: Rename binary
-      run: |
+      - name: Build
+        run: cargo build --verbose --release
+
+      - name: Run tests
+        run: cargo test --verbose --release
+
+      - name: Rename binary
+        run: |
           cp target/release/dashpipe target/release/deco
 
-    - name: Release
-      uses: softprops/action-gh-release@v0.1.13
-      if: startsWith(github.ref, 'refs/tags/')
-      with:
-        files: |
-          target/release/deco
-    
+      - name: Release
+        uses: softprops/action-gh-release@v0.1.13
+        if: startsWith(github.ref, 'refs/tags/')
+        with:
+          files: |
+            target/release/deco
 
   # build-mac:
 
