bail workflow if not git tagged

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -23,10 +23,10 @@ jobs:
         git show --oneline --no-patch
     
     - name: verify tag check
-      if: startsWith(github.ref, 'refs/tags/')
+      if: ! startsWith(github.ref, 'refs/tags/')
       run: |
-        echo "starts with tag"
-        echo 2 ${{ github.ref }}
+        echo "::error git checkout has no git tag"
+        exit 1
 
     - name: Build
       run: cargo build --verbose --release
